# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="false"
install:
  - source continuous-integration/travis/travis_install.sh
  - pip install -r requirements.txt
  - pip install -U pytest pytest-cov
before_script:
  - git config --global user.email "ga63nep@mytum.de"
  - git config --global user.name "Andreas Stelzer"
script:
  - python setup.py build_ext --inplace
  - pip install -e .
  - py.test
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
sudo: required
